[package]
name = "obscura-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
obscura-config = { path = "../config" }
hyper = { version = "1.3", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
bytes = "1.0"
serde_json = "1.0"

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
